- name: Install auditd package
  apt:
    name: auditd
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"
  tags:
    - security
    - audit

- name: Enable and start auditd service
  systemd:
    name: auditd
    state: started
    enabled: yes
    daemon_reload: yes
  tags:
    - security
    - audit

- name: Configure auditd
  template:
    src: auditd.conf.j2
    dest: /etc/audit/auditd.conf
    mode: '0640'
    owner: root
    group: root
  notify: Restart auditd
  tags:
    - security
    - audit


