---
- name: Load kernel modules
  shell: |
    modprobe overlay
    modprobe br_netfilter
  changed_when: true

- name: Restart containerd
  systemd:
    name: containerd
    state: restarted
    daemon_reload: yes 